-include .env


format: 
	@echo "formatting the project"
	@cargo fmt

build:
	@echo "building the project"
	@stellar contract build

test:
	@echo "testing the project tests"
	@cargo test


clippy:
	@echo "clip"
	@cargo clippy