name: Soroban Smart Contracts CI

on:
  push:
    branches: ['main']
    paths:
      - 'apps/contracts/**'
  pull_request:
    branches: ['main']
    paths:
      - 'apps/contracts/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
      - name: Install Rust target for Soroban
        run: |
          source $HOME/.cargo/env
          rustup target add wasm32v1-none
      - name: Install Stellar CLI with Homebrew
        run: |
          brew update
          brew install stellar-cli
          stellar --version
      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Build Cargo project
        run: |
          source $HOME/.cargo/env
          cargo build --verbose
        working-directory: apps/contracts

      - name: Build Soroban contracts
        run: |
          source $HOME/.cargo/env
          for contract in contracts/*/; do
            if [ -f "$contract/Cargo.toml" ]; then
              echo "Building contract: $contract"
              stellar contract build --verbose --path "$contract"
            fi
          done
        working-directory: apps/contracts

      - name: Run Cargo tests
        run: |
          source $HOME/.cargo/env
          cargo test --verbose
        working-directory: apps/contracts
